package se.sundsvallskommun.nodes.model;

/**
 * @author TimoMikkola
 *
 */

import java.io.Serializable;
import java.sql.Blob;
import java.sql.Timestamp;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "form_file")
@XMLElement
public class File extends GeneratedElementable implements Serializable {
	
	private static final long serialVersionUID = -6188427465428775655L;
	
	@DAOManaged(columnName = "file_id", autoGenerated = true)
	@Key
	@XMLElement(name = "FileID")
	private Integer fileID;
	
	@DAOManaged(columnName = "data", dontUpdateIfNull = true)
	private Blob fileData;
	
	@DAOManaged(columnName = "name")
	@XMLElement(name = "FileName")
	private String fileName;
	
	@DAOManaged(columnName = "filesize")
	@XMLElement(name = "FileSize")
	private Long fileSize;
	
	@DAOManaged(columnName = "date_added")
	@XMLElement(name = "DateAdded")
	private Timestamp dateAdded;
	
	@DAOManaged(columnName = "questionnaire_value_id") 
	@OneToOne
	private QuestionnaireValue questionnaireValue;

	public Integer getFileID() {
		return fileID;
	}

	public void setFileID(Integer fileID) {
		this.fileID = fileID;
	}

	public Blob getFileData() {
		return fileData;
	}

	public void setFileData(Blob fileData) {
		this.fileData = fileData;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Long getFileSize() {
		return fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	public Timestamp getDateAdded() {
		return dateAdded;
	}

	public void setDateAdded(Timestamp dateAdded) {
		this.dateAdded = dateAdded;
	}

	public QuestionnaireValue getQuestionnaireValue() {
		return questionnaireValue;
	}

	public void setQuestionnaireValue(QuestionnaireValue questionnaireValue) {
		this.questionnaireValue = questionnaireValue;
	}
	
	
	
}
