package se.sundsvallskommun.nodes.model;

import java.util.List;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "form_type")
@XMLElement
public class FormType extends GeneratedElementable {
	
	@DAOManaged(columnName = "form_type_id", autoGenerated = true)
	@Key
	@XMLElement(name = "FormTypeID")
	private Integer formTypeID;
	
	@DAOManaged(columnName = "form_type_name")
	@WebPopulate(required = true)
	@XMLElement(name = "Name")
	private String name;
	
	@DAOManaged(columnName = "description")
	@WebPopulate(required = true)
	@XMLElement(name = "Description")
	private String description;
	
	@DAOManaged
	@OneToMany
	private List<Form> forms;
	
	private Boolean skipTemplateInXML = false;

	public Integer getID() {
		return formTypeID;
	}

	public void setID(Integer formTypeID) {
		this.formTypeID = formTypeID;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getSkipTemplateInXML() {
		return skipTemplateInXML;
	}

	public void setSkipTemplateInXML(Boolean skipTemplateInXML) {
		this.skipTemplateInXML = skipTemplateInXML;
	}

	public List<Form> getForms() {
		return forms;
	}

	public void setForms(List<Form> forms) {
		this.forms = forms;
	}
	
	
}
