package se.sundsvallskommun.nodes.model;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "form_questionnaire_value_note")
@XMLElement
public class Note extends GeneratedElementable {

	@DAOManaged(columnName = "note_id", autoGenerated = true)
	@Key
	@XMLElement(name = "Note")
	private Integer noteID;
	
	@DAOManaged(columnName = "note")
	@WebPopulate(required = true)
	@XMLElement(name = "note")
	private String note;
	
	@DAOManaged(columnName = "questionnaire_value_id")
	@OneToOne
	private QuestionnaireValue questionnaireValue;

	public Integer getNoteID() {
		return noteID;
	}

	public void setNoteID(Integer noteID) {
		this.noteID = noteID;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public QuestionnaireValue getQuestionnaireValue() {
		return questionnaireValue;
	}

	public void setQuestionnaireValue(QuestionnaireValue questionnaireValue) {
		this.questionnaireValue = questionnaireValue;
	}
	
}
