package se.sundsvallskommun.nodes.model;

/**
 * @author TimoMikkola
 *
 */

import java.io.UnsupportedEncodingException;
import java.util.List;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToMany;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "form_question_type")
@XMLElement
public class QuestionType extends GeneratedElementable {

	@DAOManaged(columnName = "question_type_id", autoGenerated = true)
	@Key
	@XMLElement(name = "ID")
	private Integer questionTypeID;
	
	@DAOManaged(columnName = "question_type_value")
	@WebPopulate(required = true)
	@XMLElement(name = "Type")
	private String questionType;
	
	@DAOManaged
	@OneToMany
	private List<Question> questions;
	
	public Integer getID() {
		return questionTypeID;
	}

	public void setID(Integer questionTypeID) {
		this.questionTypeID = questionTypeID;
	}

	public String getQuestionType() {
		return questionType;
	}

	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}

	public List<Question> getQuestions() {
		return questions;
	}

	public void setTemplateAttributes(List<Question> questions) {
		this.questions = questions;
	}
	
	
}
