package se.sundsvallskommun.nodes.model;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "form_question_option")
@XMLElement
public class QuestionOption extends GeneratedElementable {
	
	@DAOManaged(columnName = "question_option_id", autoGenerated = true)
	@Key
	@XMLElement(name = "value")
	private Integer questionOptionID;
	
	@DAOManaged(columnName = "question_option")
	@WebPopulate(required = true)
	@XMLElement(name = "name")
	private String option;
	
		
	@DAOManaged(columnName = "question_id")
	@XMLElement(name = "Question")
	@ManyToOne
	private Question question;
		
	
//	@DAOManaged
//	@OneToMany
//	@XMLElement(name = "SelectedValues")
//	private List<SelectedValue> selectedValues;

	public Integer getID() {
		return questionOptionID;
	}

	public void setID(Integer id) {
		this.questionOptionID = id;
	}

	public String getOption() {
		return option;
	}

	public void setOption(String option) {
		this.option = option;
	}

	public Question getQuestion() {
		return question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

//	public List<SelectedValue> getSelectedValues() {
//		return selectedValues;
//	}
//
//	public void setSelectedValues(List<SelectedValue> selectedValues) {
//		this.selectedValues = selectedValues;
//	}

	public Integer getQuestionOptionID() {
		return questionOptionID;
	}

	public void setQuestionOptionID(Integer questionOptionID) {
		this.questionOptionID = questionOptionID;
	}
	
}
