package se.sundsvallskommun.nodes.model;

import java.util.List;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "form_question")
@XMLElement
public class Question extends GeneratedElementable implements Comparable<Question> {

	@DAOManaged(columnName = "question_id", autoGenerated = true)
	@Key
	@XMLElement(name = "ID")
	private Integer questionID;
	
	@DAOManaged(columnName = "name")
	@WebPopulate(required = true)
	@XMLElement(name = "Name")
	private String name;
	
	@DAOManaged(columnName = "question_type")
	@ManyToOne(autoGet = true, autoAdd = false, autoUpdate = false)
	@XMLElement(name = "QuestionType")
	private QuestionType questionType;
	
	@DAOManaged(columnName = "description")
	@XMLElement(name = "Description")
	private String description;
	
	@DAOManaged(columnName = "required")
	@XMLElement(name = "Required")
	private Boolean required;
	
	@DAOManaged(columnName = "sort_prio")
	@XMLElement(name = "SortPrio")
	private int sortPrio;

	@DAOManaged(columnName = "enabled")
	@XMLElement(name = "Enabled")
	private Boolean enabled;
	
	@DAOManaged
	@XMLElement(name = "QuestionOptions")
	@OneToMany(autoGet = true, autoAdd = false, autoUpdate = false)
	private List<QuestionOption> questionOptions;
	
	@DAOManaged
	@OneToMany
	private List<QuestionnaireValue> questionnaireValues;
	
	@DAOManaged(columnName = "parent")
	@XMLElement(name = "Parent")
	private Integer parent;
	
	@DAOManaged(columnName = "option")
	@XMLElement(name = "Option")
	private String option;
	
	@XMLElement(name = "AttributeDetails")
	private String attributeDetails;
	
	@XMLElement(name = "ActionRequired")
	private Boolean actionRequired;
		
	public Boolean getActionRequired() {
		return actionRequired;
	}

	public void setActionRequired(Boolean actionRequired) {
		this.actionRequired = actionRequired;
	}

	public Integer getID() {
		return questionID;
	}

	public void setID(Integer questionID) {
		this.questionID = questionID;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<QuestionOption> getQuestionOptions() {
		return questionOptions;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getRequired() {
		return required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

	public int getSortPrio() {
		return sortPrio;
	}

	public void setSortPrio(int sortPrio) {
		this.sortPrio = sortPrio;
	}

	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}
	
	public List<QuestionnaireValue> getQuestionnaireValues() {
		return questionnaireValues;
	}

	public void setQuestionnaireValues(List<QuestionnaireValue> questionnaireValues) {
		this.questionnaireValues = questionnaireValues;
	}

	public Integer getQuestionID() {
		return questionID;
	}

	public void setQuestionID(Integer questionID) {
		this.questionID = questionID;
	}

	public QuestionType getQuestionType() {
		return questionType;
	}

	public void setQuestionType(QuestionType questionType) {
		this.questionType = questionType;
	}

	public void setQuestionOptions(List<QuestionOption> questionOptions) {
		this.questionOptions = questionOptions;
	}

	public String getAttributeDetails() {
		return attributeDetails;
	}

	public void setAttributeDetails(String attributeDetails) {
		this.attributeDetails = attributeDetails;
	}

	public Integer getParent() {
		return parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public String getOption() {
		return option;
	}

	public void setOption(String option) {
		this.option = option;
	}

	@Override
	public int compareTo(Question ta) {
		
		int lhs_val = this.getSortPrio();
		int rhs_val = ta.getSortPrio();
		
		int pre_result = lhs_val > rhs_val ? 1 : lhs_val < rhs_val ? -1 : 0;
		
		if (pre_result == 0) {
			lhs_val = this.getID();
			rhs_val = ta.getID();
			
			pre_result = lhs_val > rhs_val ? 1 : lhs_val < rhs_val ? -1 : 0;
			
			int result = lhs_val > rhs_val ? 1 : lhs_val < rhs_val ? -1 : 0;
			
			if (pre_result != 0 && result == 0) {
				return pre_result;
				
			}
			
			return result;
			
		} else {
			return pre_result;
			
		}
		
	}

}
