package se.sundsvallskommun.nodes.model;

/**
 * @author TimoMikkola
 *
 */

import java.util.List;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.OneToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "form_questionnaire")
@XMLElement
public class Questionnaire extends GeneratedElementable implements Comparable<Questionnaire> {

	@DAOManaged(columnName = "questionnaire_id", autoGenerated = true)
	@Key
	@XMLElement(name = "QuestionnaireID")
	private Integer questionnaireID;
	
	@DAOManaged(columnName = "form_id")
	@OneToOne(preAdd = true)
	private Form form;
	
	@DAOManaged
	@OneToMany(autoGet = false, autoAdd = true, autoUpdate = true)
	@XMLElement(name = "Values")
	private List<QuestionnaireValue> questionnaireValues;
	
	@DAOManaged(columnName = "questionnaire_status")
	@ManyToOne(autoGet = true)
	@XMLElement(name = "QuestionnaireStatus")
	private QuestionnaireStatus questionnaireStatus;
	
	@DAOManaged(columnName = "has_notes")
	@XMLElement(name = "Notes")
	private Boolean hasNotes;
	
	@DAOManaged(columnName = "has_action_required")
	@XMLElement(name = "ActionRequired")
	private Boolean hasActionRequired;
	
//	@DAOManaged(columnName = "contact_name")
	@WebPopulate(required = true)
	@XMLElement(name = "ContactName")
	private String contactName;
	
//	@DAOManaged(columnName = "register_type")
	@WebPopulate(required = true)
	@XMLElement(name = "RegisterType")
	private String registerType;
		

	public Form getForm() {
		return form;
	}
	
	public void setForm(Form form) {
		this.form = form;
	}
		
	public List<QuestionnaireValue> getQuestionnaireValues() {
		return questionnaireValues;
	}
	
	public void setQuestionnaireValues(List<QuestionnaireValue> questionnaireValues) {
		this.questionnaireValues = questionnaireValues;
	}
	
	public Integer getID() {
		return questionnaireID;
	}

	public void setID(Integer questionnaireID) {
		this.questionnaireID = questionnaireID;
	}

	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getRegisterType() {
		return registerType;
	}

	public void setRegisterType(String registerType) {
		this.registerType = registerType;
	}
	
	@Override
	public int compareTo(Questionnaire o) {
		// TODO Auto-generated method stub
		return 0;
	}

	public Boolean getHasNotes() {
		return hasNotes;
	}

	public void setHasNotes(Boolean hasNotes) {
		this.hasNotes = hasNotes;
	}

	public Boolean getHasActionRequired() {
		return hasActionRequired;
	}

	public void setHasActionRequired(Boolean hasActionRequired) {
		this.hasActionRequired = hasActionRequired;
	}

	public QuestionnaireStatus getQuestionnaireStatus() {
		return questionnaireStatus;
	}

	public void setQuestionnaireStatus(QuestionnaireStatus questionnaireStatus) {
		this.questionnaireStatus = questionnaireStatus;
	}
	
	
	
}
