package se.sundsvallskommun.nodes.model;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "form_selected_value")
@XMLElement
public class SelectedValue extends GeneratedElementable {

	@DAOManaged(columnName = "selected_value_id", autoGenerated = true)
	@Key
	@XMLElement(name = "SelectedValueID")
	private Integer selectedValueID;
	
	@DAOManaged(columnName = "questionnaire_value_id")
	@ManyToOne
	private QuestionnaireValue questionnaireValue;
	
	@DAOManaged(columnName = "value")
	@WebPopulate(required = true)
	@XMLElement(name = "Value")
	private String value;
	
	public Integer getSelectedValueID() {
		return selectedValueID;
	}

	public void setSelectedValueID(Integer selectedValueID) {
		this.selectedValueID = selectedValueID;
	}

	public QuestionnaireValue getQuestionnaireValue() {
		return questionnaireValue;
	}

	public void setQuestionnaireValue(QuestionnaireValue questionnaireValue) {
		this.questionnaireValue = questionnaireValue;
	}

//	public QuestionValue getQuestionValue() {
//		return questionValue;
//	}
//
//	public void setQuestionValue(QuestionValue questionValue) {
//		this.questionValue = questionValue;
//	}
//
//	public SubQuestionValue getSubQuestionValue() {
//		return subQuestionValue;
//	}
//
//	public void setSubQuestionValue(SubQuestionValue subQuestionValue) {
//		this.subQuestionValue = subQuestionValue;
//	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	
}
