package se.sundsvallskommun.nodes.beans;

import java.io.Serializable;
import java.sql.Timestamp;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "node_files")
@XMLElement
public class NodeFileInfo extends GeneratedElementable implements Serializable {
	
	private static final long serialVersionUID = 8320347336829544042L;

	@DAOManaged(columnName = "facility_file_id", autoGenerated = true)
	@Key
	@XMLElement
	private Integer nodeFileID;


	@DAOManaged(columnName = "name")
	@XMLElement
	private String fileName;
	
	
	@DAOManaged(columnName = "filesize")
	@XMLElement
	private Long fileSize;
	
	@DAOManaged(columnName = "date_added")
	@XMLElement
	private Timestamp dateAdded;	

	
	public Integer getFacilityFileID() {
		return nodeFileID;
	}

	public void setFacilityFileID(Integer nodeFileID) {
		this.nodeFileID = nodeFileID;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	
	public Long getFileSize() {
		return fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	public Timestamp getDateAdded() {
		return dateAdded;
	}

	public void setDateAdded(Timestamp dateAdded) {
		this.dateAdded = dateAdded;
	}
	
}