package se.sundsvallskommun.nodes.beans;

import java.io.Serializable;
import java.util.List;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "node_global_tags")
@XMLElement(name="tag")
public class NodeTag extends GeneratedElementable implements Serializable {
	
	private static final long serialVersionUID = -6188427465428775655L;

	@DAOManaged(columnName = "tag_id", autoGenerated = true)
	@Key
	@XMLElement(name="value")	
	private Integer facilityTagID;
	
	@DAOManaged
	@ManyToMany(linkTable="node_tags",autoAdd=true)
	private List<NodeOwner> parentNode;

	@DAOManaged(columnName = "name")
	@XMLElement(name="name")
	@WebPopulate(required = true)
	private String tagName;

	public Integer getFacilityTagID() {
		return facilityTagID;
	}

	public void setFacilityTagID(Integer facilityTagID) {
		this.facilityTagID = facilityTagID;
	}

	public String getTagName() {
		return tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}
	
	
}